en:
  error:
    deprecation:
      include_base: "deprecated: don't include Cupcakinator::Base directly"
    config_not_found: "Can't find Cupcakinator configured config file %{filename}\nCupcakinator options:\n%{options}"
    config_invalid: "Cupcakinator configure config file %{filename} invalid\nOriginal error: %{message}"